export const MATCHING_CONFIG = {
  COMPATIBILITY_FLOOR: 0.55,

  WEIGHTS: {
    VALUES: 0.25,
    QUALITIES: 0.25,
    LIFE_ANSWERS: 0.20,
    LIFESTYLE: 0.15,
    PHYSICAL: 0.15,
  },

  MAX_INTRODUCTIONS_PER_DAY: 3,
  INTRODUCTION_TTL_DAYS: 5,
};
